[package]
name = "obj2voxel"
version = "0.1.0"
authors = ["Mario Geiger <geiger.mario@gmail.com>"]

[dependencies]
obj = "0.7.0"
clap = "2.19"
npy = "*"
npy-derive = "*"
kiss3d = "0.9.0"
nalgebra = "0.12"
