[package]
name = "obj2voxel"
version = "0.2.0"
authors = ["Mario Geiger <geiger.mario@gmail.com>"]

[dependencies]
obj = "0.7.0"
clap = "2.19"
npy = "0.2.2"
npy-derive = "0.2.1"
kiss3d = "0.9.0"
nalgebra = "0.12"
